### ISSUE TITLE
log4j2 format missing MDC information 

### ISSUE THREAD

**Issue by andrempo** [newrelic/java-log-extensions#13]
The MDC information is not been sent to new relic.
Ont he logback implementation the values are added to the message: 

https://github.com/newrelic/java-log-extensions/blob/bdf75e7595aeb6e7739d070f8487398228e14d5f/logback/src/main/java/com/newrelic/logging/logback/NewRelicJsonLayout.java#L57

This information is also available for log4j2 as event.getContextData()

**Comment by jeffalder** [comment]
@andrempo - thanks for opening this. Is this something you would feel comfortable submitting a pull request for? It would be welcome.

Note that the latest version of the log4j2 extension (which is not yet released) requires log4j 2.13 (which is very recent). Also note that the latest version does also inject data into the MDC and pulls it back out.

**Comment by andrempo** [comment]
Hi @jeffalder, do you know when the new version will be available? Maybe i can just update to it.

**Comment by jeffalder** [comment]
@andrempo Sorry for the long-delayed response. I'm getting around to publishing the next version of the extensions. These will not include MDC yet. It should be a pretty quick change to the extension, though, now that the linking metadata is going into the MDC.

**Comment by jef** [comment]
I'm sorry, but maybe I'm not following. Will the new version of log4j2 extension include the MDC?

**Comment by jeffalder** [comment]
@jef Sorry, not yet! That's why this issue is still open. It should be a relatively straightforward change [around here](https://github.com/newrelic/java-log-extensions/blob/main/log4j2/src/main/java/com/newrelic/logging/log4j2/NewRelicLayout.java#L82).

**Comment by jef** [comment]
I guess I was just confused by the [release notes](https://github.com/newrelic/java-log-extensions/releases/tag/v2.0). I'll see if I can make a PR to fix!

Thanks @jeffalder

**Comment by jeffalder** [comment]
@jef That'd be awesome and much appreciated.

**Comment by natisherpa** [comment]
Any news? I too have been looking for my MDC (Thread context) information in the logs, when I came across this little issue. Any specific reason the Log4J2 appender doesn't support this must-have functionallity?

**Comment by jef** [comment]
From my end: I probably will not be working on this. Sorry for any assumptions made 😢

**Comment by natisherpa** [comment]
@jef thanks for your prompt reply. Does it mean that as long as I'm using Log4J2 with NR I won't be able to log MDC data?

**Comment by jef** [comment]
> @jef thanks for your prompt reply. Does it mean that as long as I'm using Log4J2 with NR I won't be able to log MDC data?

Not exactly. New Relic's templated logger will not suffice with MDC information, you'll have to use your own.

This is what my configuration currently looks like:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
	<Appenders>
		<Console name="PrettyConsole" target="SYSTEM_OUT" follow="true">
			<PatternLayout>
				<Pattern>%clr{%5level} [%10.10thread] %clr{%-30.30logger{1.}}{cyan} [%clr{%method:%line}{magenta}]: %message %clr{%MDC}{yellow}%n%xwException</Pattern>
			</PatternLayout>
		</Console>

		<Console name="JsonConsole" target="SYSTEM_OUT" follow="true">
			<JsonLayout complete="false" compact="true" eventEol="true" properties="true" />
		</Console>

		<Sentry name="Sentry" />

		<Routing name="Router">
			<Routes pattern="$${env:ENVIRONMENT:-}">
				<Route ref="PrettyConsole" key="localhost"/>
				<Route ref="JsonConsole" />
			</Routes>
		</Routing>
	</Appenders>

	<Loggers>
		<Root level="info">
			<AppenderRef ref="Router" />
			<AppenderRef ref="Sentry" level="warn" />
		</Root>
	</Loggers>
</Configuration>
```

You won't need the `Sentry` key, but if you use Sentry, then it's nice to have.

You can read more about the `PatternLayout` on [Log4j2's documentation](https://logging.apache.org/log4j/2.x/manual/layouts.html#PatternLayout). The `Routing` portion has to do what logger to use.

If I am developing locally, I want to be able to read the logs well (based on environment variable `ENVIRONMENT=localhost`). Otherwise, I use the JSON Logging, which New Relic understands.

---

If you just want to get this working with New Relic and don't care about what is shown locally and don't have Sentry, use this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN">
	<Appenders>
		<Console name="JsonConsole" target="SYSTEM_OUT" follow="true">
			<JsonLayout complete="false" compact="true" eventEol="true" properties="true" />
		</Console>
	</Appenders>

	<Loggers>
		<Root level="info">
			<AppenderRef ref="JsonConsole" />
		</Root>
	</Loggers>
</Configuration>
```

**Comment by natisherpa** [comment]
Thanks @jef. This is awseome. I already have the appenders I need to view logs locally, I was simply under the impression I cannot customize NewRelicLayout to add the MDC "manually"...

**Comment by jef** [comment]
Ah! Yeah, I could totally see how that's confusing. It not as obvious as I would like myself.

Glad I could help! 😊

**Comment by kford-newrelic** [comment]
Thank you for this suggested enhancement. Unfortunately, we do not have the engineering capacity to take up this request. If any contributors are ever interested to do some coding however, we would gladly review any PR(s) submitted.
