### ISSUE TITLE
Allow MAX_STACK_SIZE to be configured in NewRelicEncoder

### ISSUE THREAD

**Issue by longwa** [newrelic/java-log-extensions#29]
The NewRelicEncoder for logback uses the NewRelicJsonLayout to encode stack traces in log messages.

The layout has a hardcoded stack size of 10 lines, which is way too small for Groovy programs which produce large amounts of fluff in their stacks.

It would be ideal if the encoder could take the maxStackSize as a parameter when creating it:

```
 encoder(com.newrelic.logging.logback.NewRelicEncoder) {
    maxStackSize = 50
}
```

It might also be useful to be able to add a stack trace filter of some kind, maybe a Regex expression that could be matched as an exclusion for stack trace lines.

**Comment by jeffalder** [comment]
The last time I checked, New Relic log attributes have a size limit, which is why it's so low. Have you experimented to see what kind of results you get?

**Comment by longwa** [comment]
Let me do some additional testing and see what it looks like in the NR Log UI. I did confirm my PR works locally to add the additional lines to the stack trace.

If the attribute size is the limiting factor, maybe it would be better to go the filter route so that more important context could be included in the 10 lines that are allowed. Most of the time, for our application (Groovy/Grails), the last 10 lines are a bunch of java.reflect or org.groovy code b/c of the way groovy works reflectively most of the time. If I could filter the StackTraceElement using a regex expression passed to the Encoder, I could at least catch the last 10 lines of our application code for context.

I'll let you know what I see when trying to send the larger stack over.
