### ISSUE TITLE
Use singleton JsonFactory instance

### ISSUE THREAD

**Issue by pontello** [newrelic/java-log-extensions#31]
A quote form [jackson](https://fasterxml.github.io/jackson-core/javadoc/2.6/com/fasterxml/jackson/core/JsonFactory.html) docs:

> Factory instances are thread-safe and reusable after configuration (if any). Typically applications and services use only a single globally shared factory instance, unless they need differently configured factories. Factory reuse is important if efficiency matters; most recycling of expensive construct is done on per-factory basis.

We should have some performance improvement by sharing the same JsonFactory instance [here](https://github.com/newrelic/java-log-extensions/blob/main/logback/src/main/java/com/newrelic/logging/logback/NewRelicJsonLayout.java#L30) instead of creating a new one for each log entry.

**Comment by gstoupis** [comment]
Hi there! I took a shot at this one. It's my first one, so I don't know if I followed the correct procedure. 

Let me know if you need me to change anything. Thanks!

**Comment by gfuller1** [comment]
@pontello it looks like this fix made it in! I'm going to close this issue. Thanks for helping us improve the product!
