### ISSUE TITLE
JUL with Tomcat documentation update

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/java-log-extensions#33]
There is a known issue that makes the documentation 
https://github.com/newrelic/java-log-extensions/blob/main/jul/README.md
not work correctly when deploying into tomcat.  

The issue seems to be:
* the NR jul classes (and their dependencies) need to be on the Tomcat system classloader
* the NR jul classes should NOT be in the application classloader
* the `logging.properties` should be in the application's `WEB-INF/classes` dir (from the war)

The documentation should be updated to reflect the complexities of using jul with tomcat, perhaps with an working example.

**Comment by kford-newrelic** [comment]
Not selected for the agent roadmap.
