### ISSUE TITLE
Feature Request: Logging Nested Exception Stack Traces 

### ISSUE THREAD

**Issue by smarkwell** [newrelic/java-log-extensions#34]
Version: ```com.newrelic.logging:log4j1:2.1```

It would be nice if ```https://github.com/newrelic/java-log-extensions/blob/main/log4j1/src/main/java/com/newrelic/logging/log4j1/NewRelicLayout.java#L84``` handled exceptions/throwables that are nested with additional logging.  As the current code stands it only displays the top level stack trace when a throwable is associated with a logging event.  

Ideally this should be a configuration option for the layout so it doesn't break backwards compatibility with existing behavior.

**Comment by kford-newrelic** [comment]
@smarkwell thank you for this suggested enhancement. Unfortunately, we don't have the engineering capacity to take this up at this time. If you're ever interested in doing some agent coding, we will gladly review any PR(s) you submit.
