### ISSUE TITLE
log4j1 - stack trace size

### ISSUE THREAD

**Issue by adamsApzumi** [newrelic/java-log-extensions#39]
Please add `maxStackSize` parameter to `NewRelicLayout`. Now it is limited to 10.

(Migrate to Jira)

**Comment by kford-newrelic** [comment]
May target for future sustainability work...

**Comment by jasonjkeller** [comment]
I think we should be fine increasing the default to somewhere around 500 lines without hitting the ingest limits on attribute size.

**Comment by kford-newrelic** [comment]
Unfortunately we were not able to prioritize this for the coming Jan-Mar quarter. Will consider for a future quarter.
