### ISSUE TITLE
MDC context is not retained when using logback 1.48

### ISSUE THREAD

**Issue by vivekkothari** [newrelic/java-log-extensions#76]
## Description
# MDC context is not retained when using logback 1.48

## Expected Behavior
I expect the MDC context to be correctly retained when using the `com.newrelic.logging.logback.NewRelicEncoder`.

## Troubleshooting results
Consistently reproducible. Just use this encoder with logback 1.48, none of the MDC keys are retained.
The probable logback commit which caused this to break: https://jira.qos.ch/browse/LOGBACK-1742 

## Steps to Reproduce
Consistently reproducible. Just use this encoder with logback 1.48, none of the MDC keys are retained.

## Your Environment
JVM: 17.0.7 correto.
NR agent: 8.3

## Additional context
None

**Comment by kford-newrelic** [comment]
@vivekkothari thanks for submitting this issue; we won't be able to take this up during the current Jul-Sep quarter but we will consider this for a future quarter

**Comment by vivekkothari** [comment]
If you can give me few pointers I am happy to fix it.
