### ISSUE TITLE
Update ch.qos.logback:logback-core to version 1.2.13 or latest

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/java-log-extensions#95]
### Update:
This ticket has been updated. The original security scan requested an update to 1.2.7+ (fulfilled, we're on 1.2.9), but a separate vulnerability with 1.2.9 also needs addressing. Upgrade logback-core to 1.2.13. 

### Description
A newer version of the `ch.qos.logback:logback-core` artifact is available; we want to update this log extension to use it.

### Acceptance Criteria
Retest and release a new log extension, with an updated dependency.

### Design Consideration/Limitations
N/A

### Dependencies
`ch.qos.logback:logback-core`

### Additional context
Original Jira - [NR-282833](https://new-relic.atlassian.net/browse/NR-282833)

[NR-282833]: https://new-relic.atlassian.net/browse/NR-282833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kanderson250** [comment]
This looks to be a false positive as the [logback-core dependency](https://github.com/newrelic/java-log-extensions/blob/4a2daa3c01b87f9a61299159f407d1d4fdb23b68/logback/build.gradle.kts#L24) is currently 1.2.9. Closing.

**Comment by kanderson250** [comment]
Reopening due to a separate vulnerability in logback 1.2.9 that was resolved with 1.2.13 and modifying the ticket description.
